config-version: 2
version: "1.4.6"

name: "dbt_submodules_test"
profile: "dbt_submodules_test"

model-paths: ["models", "exposures"]
macro-paths: ["macros"]

models:
  elementary:
    +schema: elementary

seeds:
  dbt_submodules_test:
    +schema: seeds

vars:
  backfill: False
  increment_start: "1999-01-01"
  increment_end: "2999-01-01"

  users:
    - user_1
    - user_2
